### ISSUE TITLE
get-contract-instance returns an AbstractContract

### ISSUE THREAD

**Issue by joshma91** [trufflesuite/drizzle-utils#102]
`get-contract-instance` fails to get the proper contract instance, but retrieving the  instance without use of `drizzle-utils` is working for me. Following is the code I've tried:

```javascript
import React from 'react'
import getWeb3 from "@drizzle-utils/get-web3"
import getContractInstance from "@drizzle-utils/get-contract-instance"
import createDrizzleUtils from "@drizzle-utils/core"
 
export default class Web3Container extends React.Component {
  state = { web3: null, accounts: null, contract: null };
 
  async componentDidMount () {
    try {
      const web3 = await getWeb3()
      const drizzleUtils = await createDrizzleUtils({ web3 })
      const accounts = await drizzleUtils.getAccounts()
      const contract = await getContractInstance ({
        web3,
        artifact: this.props.contractJSON
      })
      console.log(contract)
      this.setState({ web3, accounts, contract })
    } catch (error) {
      alert(
        `Failed to load web3, accounts, or contract. Check console for details.`
      )
      console.log(error)
    }
  }
}
```
This `AbstractContract` is what is logged out as the `contract`. I'm not able to use any of my contract's functions when this is returned. 
![image](https://user-images.githubusercontent.com/9612111/57432566-15e39380-71eb-11e9-8617-f63f76f98bc9.png)

However, when I revert to using `web3^1.0.0-beta.35` and manually obtain my web3 instance through MetaMask, I'm able to successfully obtain my contract instance using `new web3.eth.Contract(abi, deployedAddress)`.

**Comment by adrianmcli** [comment]
`getContractInstance` exists within `core`, so you could just do `drizzleUtils.getContractInstance()` and not have to pass in a web3.

Also, can you provide a reproduction repo for this? I want to make sure this is reproducible for a more basic case.

**Comment by joshma91** [comment]
Sure, I'll have a reproduction repo for this shortly.

**Comment by joshma91** [comment]
@adrianmcli I tried recreating this based on the React Truffle Box, but couldn't do so. Both versions of getting the contract work as shown below:

```javascript
      const instance = await drizzleUtils.getContractInstance({
        artifact: SimpleStorageContract,
      });

      // method from drizzle-utils/get-contract-instance
      const instance2 = await getContractInstance({
        web3,
        artifact: SimpleStorageContract,
      });
```
Reproduction repo here: https://github.com/joshma91/drizzle-utils-contract-reprod/blob/master/client/src/App.js#L26

We can probably chalk this up to my user error.

**Comment by adrianmcli** [comment]
Good to know, thanks!
