### ISSUE TITLE
Get balance stream

### ISSUE THREAD

**Issue by honestbonsai** [trufflesuite/drizzle-utils#103]
I'd like to get a stream of balance for an address. DRC has that [functionality](https://github.com/trufflesuite/drizzle-react-components/blob/develop/src/AccountData.js).

The closest thing DU has is `contract-state-stream`, but that's for contracts only and comes with a lot of other info you might not need.

**Comment by adrianmcli** [comment]
That's a great idea, I'm going to make this one of the TODOs for the conference. That means this should be operational within 2 weeks time.

**Comment by adrianmcli** [comment]
If you want to start it, feel free.

**Comment by honestbonsai** [comment]
@adrianmcli Yea, I'll start it.

**Comment by honestbonsai** [comment]
@adrianmcli Take a look at https://github.com/trufflesuite/drizzle-utils/tree/feature/get-balance-stream. Having some trouble getting the balance test to actually run. 

I did a `npm test` of the entire repo and seems like there's a lot of failing tests, not sure if something's wrong with the test initialization or not.

**Comment by adrianmcli** [comment]
The tests seem to work fine, with the exception of the balance checking test "_can track balance of addresses_":

```
Error: expect(received).toEqual(expected)

Difference:

- Expected
+ Received

  Array [
-   "0",
+   "98999958000000000000",
  ]
```

By default, a Ganache test chain will put 99 ETH into the first 10 accounts I believe. Maybe this is the issue?

**Comment by honestbonsai** [comment]
Odd, I couldn't even get to that stage @adrianmcli, perhaps I'll wipe my `node_modules` and try again

**Comment by honestbonsai** [comment]
Fixed the issue, PR is up
