### ISSUE TITLE
Refactor balance stream

### ISSUE THREAD

**Issue by adrianmcli** [trufflesuite/drizzle-utils#114]
Several issues regarding naming that slipped my review last time:

1. Instead of `get-balance-stream`, the package name should be `balance-stream` to be in line with the other stream packages.

2. Instead of `createBalanceStream$`, the variable name (in tests and the actual code) should be `createBalance$` since the `$` is already read as "stream". This is the way it is used in the rest of the codebase as well.

Would like your thoughts, @honestbonsai

**Comment by honestbonsai** [comment]
Sounds good to me @adrianmcli

**Comment by adrianmcli** [comment]
still need to do this
