### ISSUE TITLE
Migrating from Web3.js to Ethers.js

### ISSUE THREAD

**Issue by adrianmcli** [trufflesuite/drizzle-utils#131]
Part of why PR #130 was created (and the focus on EIP-1193 provider instance rather than Web3 instance) is that we want to be less reliant on Web3.js. In the short-to-mid term, I see us moving towards having Ethers.js internals and removing Web3.js completely from this library.

As a result, it needs to be coordinated as to which packages will remain/be discarded/significantly modified.

- `contract-call-stream`: Likely to be discarded as it is trivial to create same functionality w/ `newBlock$`
- `contract-event-stream`: Likely to remain, but return values will likely be different. Tests will have to be changed.
- `contract-state-stream`: This never required Web3 itself, just the state decoder from Truffle.
- `core`: This will be re-architected to accept a provider for instantiation and will no longer support web3-specific calls.
- `current-account-stream`: EIP-1193 makes it very easy to listen to this, so this might be discarded.
- `get-accounts`: Same as `current-account-stream`; There's no magic to this either, so this might be discarded as well.
- `get-balance-stream`: This is worthwhile and will likely stay, but will have internal calls replaced with Ethers.js calls, which might affect the return values. Tests will have to be changed.
- `get-contract-instance`: This might be a good independent package as a convenience function to accept either ABI/truffle artifact/something else. However, I can also see this being discarded as well.
- `get-web3`: This is no longer necessary if we are not focusing on Web3.js.
- `new-block-stream`: This will have to be heavily re-architectured. Especially since there is still no reliable way to see if a provider supports subscriptions or not, so we will only support polling for now. Return values will also be different with Ethers.js vs Web3.js.
- `test-chain`: This can be simplified as we drop support for Web3.js, we don't actually need to return Web3 instances anymore, just the provider is sufficient.

**Comment by adrianmcli** [comment]
still need this

**Comment by caseykey** [comment]
So has Drizzle moved to accepting Ethers.js? It sucks if we have to choose between using Ethers.js or Drizzle.

**Comment by adrianmcli** [comment]
@caseykey I no longer work for Truffle, but here's the chart to compare usage of Web3.js vs Ethers.js: https://npmcharts.com/compare/web3,ethers

The community seems to be moving towards Ethers.js rapidly, and indeed I have stopped using Web3.js personal projects. If you choose not to use Drizzle, I highly recommend rolling your own state management solution w/ React hooks via [Unstated](https://github.com/jamiebuilds/unstated-next). Redux usage is no longer as ubiquitous as it once was.
