### ISSUE TITLE
Feat: Create a stream of events from a contract

### ISSUE THREAD

**Issue by adrianmcli** [trufflesuite/drizzle-utils#30]
This allows the user to easily subscribe to a contract's events and do whatever they want with it.

Potentially helpful links:

- https://ethereum.stackexchange.com/questions/2024/how-to-access-the-event-log-by-knowing-the-contract-address-web3
- https://web3js.readthedocs.io/en/1.0/web3-eth-contract.html#events-allevents

**Comment by adrianmcli** [comment]
This is a common request from beginners (including myself in the past): https://www.reddit.com/r/ethereum/comments/3ktzad/how_do_you_get_the_return_value_of_a_function/

Events are probably the best solution for that problem-case.

**Comment by honestbonsai** [comment]
In reference to your use case of getting a return value:

If you await/.then the `send()` PromiEvent of web3 1.0, you get the receipt which should contain the events (if any were emitted due to the tx).

**Comment by honestbonsai** [comment]
Some work in progress under branch `contract-event-stream`

**Comment by adrianmcli** [comment]
Might impact us, might not; probably not.

https://github.com/trufflesuite/ganache-core/issues/295
