### ISSUE TITLE
Chore: Refactor core package

### ISSUE THREAD

**Issue by adrianmcli** [trufflesuite/drizzle-utils#34]
Core package hasn't been touched in a long time. Once the other packages are stabilized (and relatively well-tested), we should work on the core package API.

One thing that I would like to do is to move to a class-free approach, but more research has to be done to make sure it would work fine.

**Comment by honestbonsai** [comment]
Docs need to be updated too

**Comment by adrianmcli** [comment]
> seems like `core` has already moved to class-free

Yes, I did that for the hackathon.

> Docs need to be updated too

Yes, we have a lot of work to do. The unglamourous and boring work of polishing up a library before release.
