### ISSUE TITLE
contract-call-stream doesn't need promise or async

### ISSUE THREAD

**Issue by honestbonsai** [trufflesuite/drizzle-utils#40]
Pretty sure `contract-call-stream` doesn't need promise or async. We prob can just return the observable.

See:
https://github.com/trufflesuite/drizzle-utils/blob/master/packages/contract-call-stream/index.js#L5

This might also be in other packages, didn't look at the rest yet.

**Comment by adrianmcli** [comment]
I think `new-block-stream` can also be converted.
