### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by juharris** [trufflesuite/drizzle-utils#48]
When is the next release planned? A couple of packages like get-contract-instance have useful updates that I'd like to use.

**Comment by adrianmcli** [comment]
@juharris We're actively working on this. Hopefully we can make an official beta release at the end of next week.

**Comment by adrianmcli** [comment]
@juharris I have released 0.2.0 prior to the EDCON talk, so it is "relatively" stable for now. That being said, there are some issues that still need fixing, like #98 for example. Please give this a try and let us know if you have any feedback/bugs to report.

**Comment by adrianmcli** [comment]
Closing for now, thanks for creating the issue.
