### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by honestbonsai** [trufflesuite/drizzle-utils#60]
Existing `README`s are out of date and some packages are missing `README` content all together.

**Comment by adrianmcli** [comment]
- [ ] Add [DocToc](https://github.com/thlorenz/doctoc) for a Table of Contents

**Comment by adrianmcli** [comment]
We should also explain:

- [ ] what the `core` package does
- [ ] how `core` is a state container for your `web3` and `newBlock$`
- [ ] how using `core` is different from using the individual packages

@joshma91 was confused about the difference from using the method referred to by `drizzleUtils.myMethod` versus using the package directly.

Granted, maybe this could be alleviated if we had clear examples on the README so people don't need to know anything about the individual packages at all.

Using individual packages is an "advanced" use-case, after all.

**Comment by adrianmcli** [comment]
Probably should also try to do this before EthCon Korea on May 27th.
