### ISSUE TITLE
Additional options for creating event streams

### ISSUE THREAD

**Issue by adrianmcli** [trufflesuite/drizzle-utils#62]
This should probably go in the `core` package, I think?

### Current usage

We currently require ABI and address:

```js
const event$ = await drizzleUtils.createContractEvent$({
  abi: contractArtifact.abi,
  address: contractArtifact.networks[networkId].address
})
```

### Additional usage options

It would be good if we could support the following alternatives:

#### Web3 contract instance

```js
const event$ = await drizzleUtils.createContractEvent$({
  instance: contractInstance
})
```

#### Truffle JSON artifact

```js
const event$ = await drizzleUtils.createContractEvent$({
  artifact: contractArtifact
})
```

**Comment by adrianmcli** [comment]
### Difficulty for passing in the artifact

If we allow users to pass in just the artifact, that means we need to return a Promise. This is because in order to find the address of the deployed contract from the artifact, we need the network ID:

```
contractArtifact.networks[networkId].address
```

And the Web3 [method](https://web3js.readthedocs.io/en/1.0/web3-eth-net.html#returns) for finding a network ID returns a Promise, thus requiring the entire function to be asynchronous.

@honestbonsai any thoughts on this?

P.S. As for being able to pass in a Web3 Contract Instance, I haven't looked at that yet.

**Comment by honestbonsai** [comment]
@adrianmcli I don't really have an issue with making it async. If we need the user to get the network ID themselves, that's going to be inside another async method anyways.

**Comment by adrianmcli** [comment]
@honestbonsai Okay, I'll make this async then. But isn't it kind of weird to the user that creating state streams is synchronous, but for events, it is asynchronous?

Maybe we should make it all asynchronous so that it's easier on consumers of the library?

**Comment by honestbonsai** [comment]
@adrianmcli Hmm, yea that's a good point. Yea making everything async would probably be easier from a user standpoint. 

But it should be done at the `core` level (where the user will interact with the lib) rather than the package level imo. So if the function really doesn't need it (like state stream) we don't need to make it async.

**Comment by adrianmcli** [comment]
Sounds good, thanks for talking it out with me.
