### ISSUE TITLE
Enhance contract-state-stream

### ISSUE THREAD

**Issue by honestbonsai** [trufflesuite/drizzle-utils#69]
Refactor and add README

**Comment by adrianmcli** [comment]
**README**

- [ ] Support inheritance by just letting the user pass in the array of artifacts
- [ ] Allow user to pass in a `networkId` and `address`, and we can patch the `artifact` for them (like what we do [here](https://github.com/trufflesuite/drizzle-utils/blob/master/packages/contract-state-stream/__tests__/node_env.js#L30-L38))

**Comment by adrianmcli** [comment]
The feature requests will have to wait until after initial alpha/beta release, so I have changed the title to "enhance" rather than "polish".

**Comment by adrianmcli** [comment]
We can keep this open.

**Comment by adrianmcli** [comment]
Actually gonna shelve this for now until the decoder API stabilizes. Some changes are due to happen here: https://github.com/trufflesuite/truffle/pull/2044
