### ISSUE TITLE
Polish get-web3

### ISSUE THREAD

**Issue by honestbonsai** [trufflesuite/drizzle-utils#73]
Refactor and add README

**Comment by adrianmcli** [comment]
**README TODOs**
- [ ] Fix typo: "fallbakc"
- [ ] Indicate that the different cases are checked in the described order
  - i.e. _the provider to be used is determined in the following order_
- [ ] Separate usage examples into different code blocks (right now, there are multiple `const` declarations of the same name)
- [ ] Explicitly indicate support for the following environments: Node/Browser/React-Native
